# Setup
title:        블로그임
tagline:      시범운영중
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Jihye Lee
  url:        http://yourhomepage.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
future: true